/* Enki Registry — seed data.
   These entries are illustrative examples to demonstrate the registry format.
   Real entries are community-submitted and human-reviewed before listing. */

window.ENKI_SEED = [
  {
    id: 'clippy',
    repo: 'paulfxyz/clippy',
    name: 'Clippy',
    url: 'https://clippy.legal',
    desc: 'AI contract analyst that reviews, redlines and explains legal documents in plain language.',
    tools: ['Perplexity Computer'],
    models: ['Claude Sonnet 4.5', 'GPT-5'],
    vibe: 98,
    cost: 210,
    date: '2026-05-02',
    sample: true,
  },
  {
    id: 'junk',
    repo: 'paulfxyz/junk',
    name: 'Junk',
    url: 'https://thejunk.app',
    desc: 'Cross-platform floating scratchpad that lives above every window — capture anything, everywhere.',
    tools: ['Claude Code'],
    models: ['Claude Opus 4.1'],
    vibe: 95,
    cost: 145,
    date: '2026-03-18',
    sample: true,
  },
  {
    id: 'mercury',
    repo: 'paulfxyz/mercury',
    name: 'Mercury',
    url: 'https://github.com/paulfxyz/mercury',
    desc: 'Multi-model inquiry app: ask once, get a consensus answer synthesised across frontier models.',
    tools: ['Perplexity Computer'],
    models: ['GPT-5', 'Claude Sonnet 4.5', 'Gemini 2.5 Pro'],
    vibe: 100,
    cost: 95,
    date: '2026-01-27',
    sample: true,
  },
  {
    id: 'hollr',
    repo: 'paulfxyz/hollr',
    name: 'Hollr',
    url: 'https://github.com/paulfxyz/hollr',
    desc: 'Encrypted public messaging and link platform — shout into the void, keep the keys.',
    tools: ['Claude Code', 'Cursor'],
    models: ['Claude Sonnet 4.5'],
    vibe: 92,
    cost: 180,
    date: '2025-11-09',
    sample: true,
  },
  {
    id: 'mang',
    repo: 'paulfxyz/mang',
    name: 'Mang',
    url: 'https://github.com/paulfxyz/mang',
    desc: 'Natural-language-to-terminal CLI written in Rust — describe the command, mang runs it.',
    tools: ['Claude Code'],
    models: ['Claude Opus 4.1', 'Qwen3-Coder (local)'],
    vibe: 100,
    cost: 62,
    date: '2025-12-14',
    sample: true,
  },
  {
    id: 'tetris',
    repo: 'paulfxyz/tetris',
    name: 'Tetris by Paul',
    url: 'https://github.com/paulfxyz/tetris',
    desc: 'A polished browser Tetris, vibe-coded end-to-end in one afternoon and shipped to Product Hunt.',
    tools: ['Perplexity Computer'],
    models: ['Claude Sonnet 4.5'],
    vibe: 100,
    cost: 9,
    date: '2026-04-11',
    sample: true,
  },
];

/* Enki Model Registry — open-weight models validated by members.
   Focus: models best adapted to self-hosting on limited hardware — a laptop,
   a desktop, even a phone. Prices: hosted-API reference rates per 1M tokens
   (Aug 2026); self-hosting trades those for hardware + energy — never "free".
   Sources: openrouter.ai, artificialanalysis.ai, mistral.ai/pricing,
   pricepertoken.com, cloudprice.net, prismml.com, allenai.org. */

window.ENKI_MODELS = [
  /* ——— Desktop class · 12–32GB GPU or Mac ——— */
  {
    id: 'qwen36-27b',
    name: 'Qwen3.6 27B',
    maker: 'Alibaba Qwen',
    license: 'Apache-2.0 family',
    priceIn: '$0.29',
    priceOut: '$2.40',
    selfHost: 'Self-host ≈ $0.03–0.70 /1M · ~17GB Q4 — 24GB GPU / 32GB Mac',
    pros: ['The strongest open model that still fits one consumer GPU', '262K context, 201 languages', 'Reasoning and non-reasoning modes in one set of weights'],
    cons: ['Hosted output rate adds up on long reasoning chains', 'Needs the full 24GB card — not a thin-laptop model'],
    links: [
      { label: 'QwenLM', url: 'https://github.com/QwenLM', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/Qwen', type: 'web' },
      { label: 'Alibaba Cloud', url: 'https://www.linkedin.com/company/alibaba-cloud-computing-company', type: 'li' },
    ],
  },
  {
    id: 'gemma-4-31b',
    name: 'Gemma 4 31B',
    maker: 'Google',
    license: 'Gemma license',
    priceIn: '$0.20',
    priceOut: '$0.20',
    selfHost: 'Self-host ≈ $0.03–0.70 /1M · 24GB GPU',
    pros: ['Flat in/out pricing — easy to budget', 'Single-GPU friendly — the local starting point', 'First-class Ollama / llama.cpp support'],
    cons: ['31B dense ceiling — outclassed on hard reasoning', 'Custom license, not OSI-approved'],
    links: [
      { label: 'ai.google.dev/gemma', url: 'https://ai.google.dev/gemma', type: 'web' },
      { label: 'huggingface.co', url: 'https://huggingface.co/google', type: 'web' },
      { label: 'Google DeepMind', url: 'https://www.linkedin.com/company/googledeepmind', type: 'li' },
    ],
  },
  {
    id: 'mistral-small-4',
    name: 'Mistral Small 4',
    maker: 'Mistral AI',
    license: 'Apache-2.0',
    priceIn: '$0.15',
    priceOut: '$0.60',
    selfHost: 'Self-host ≈ $0.03–0.70 /1M · 24GB GPU',
    pros: ['Best-in-class small model for EU-hosted work', 'Runs well on a single 24GB card'],
    cons: ['Small-model ceiling on multi-step reasoning'],
    links: [
      { label: 'mistralai', url: 'https://github.com/mistralai', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/mistralai', type: 'web' },
      { label: 'Mistral AI', url: 'https://www.linkedin.com/company/mistralai', type: 'li' },
    ],
  },
  {
    id: 'qwen3-coder-next',
    name: 'Qwen3 Coder Next',
    maker: 'Alibaba Qwen',
    license: 'Apache-2.0 family',
    priceIn: '$0.12',
    priceOut: '$0.75',
    selfHost: 'Self-host ≈ $0.03–0.70 /1M · 32GB-class GPU',
    pros: ['Code planning & tool-use specialist below mid-tier pricing', '256K context'],
    cons: ['Output is 6× its input price — long generations skew costly'],
    links: [
      { label: 'QwenLM', url: 'https://github.com/QwenLM', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/Qwen', type: 'web' },
      { label: 'Alibaba Cloud', url: 'https://www.linkedin.com/company/alibaba-cloud-computing-company', type: 'li' },
    ],
  },
  {
    id: 'phi-4',
    name: 'Phi-4 14B',
    maker: 'Microsoft',
    license: 'MIT',
    priceIn: '$0.07',
    priceOut: '$0.14',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · 12GB GPU / 16GB Mac',
    pros: ['Reasoning and math far above its weight class', 'MIT license, no strings', 'Fits a 12GB card with room to spare'],
    cons: ['16K context — short for agent loops', 'Text-only'],
    links: [
      { label: 'microsoft', url: 'https://github.com/microsoft', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/microsoft', type: 'web' },
      { label: 'Microsoft', url: 'https://www.linkedin.com/company/microsoft', type: 'li' },
    ],
  },
  /* ——— Laptop class · 4–16GB ——— */
  {
    id: 'gpt-oss-20b',
    name: 'gpt-oss-20b',
    maker: 'OpenAI',
    license: 'Apache-2.0',
    priceIn: '$0.03',
    priceOut: '$0.13',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · 16GB consumer GPU / laptop',
    pros: ['Runs on a 16GB consumer GPU or recent laptop', 'Apache-2.0, no strings', 'Adjustable reasoning effort'],
    cons: ['20B-class ceiling — delegation-tier only', 'Behind newer small models on benchmarks'],
    links: [
      { label: 'openai/gpt-oss', url: 'https://github.com/openai/gpt-oss', type: 'gh' },
      { label: 'ollama.com', url: 'https://ollama.com/library/gpt-oss', type: 'web' },
      { label: 'OpenAI', url: 'https://www.linkedin.com/company/openai', type: 'li' },
    ],
  },
  {
    id: 'bonsai-27b',
    name: 'Bonsai 27B',
    maker: 'PrismML',
    license: 'Apache-2.0',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · 5.9GB ternary laptop / 3.9GB 1-bit phone',
    pros: ['27B-class reasoning in 3.9GB — the first of its size to run on a phone', '262K context, multimodal, tool calling', '~11 tok/s on an iPhone 17 Pro Max, fully offline'],
    cons: ['1-bit quantisation keeps ~90% of full-precision quality — not 100%', 'Needs recent silicon (MLX / CUDA / WebGPU kernels)'],
    links: [
      { label: 'prismml.com', url: 'https://prismml.com', type: 'web' },
      { label: 'huggingface.co', url: 'https://huggingface.co/prism-ml', type: 'web' },
    ],
  },
  {
    id: 'qwen35-9b',
    name: 'Qwen3.5 9B',
    maker: 'Alibaba Qwen',
    license: 'Apache-2.0 family',
    priceIn: '$0.05',
    priceOut: '$0.15',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · 6.6GB — any recent laptop',
    pros: ['Rock-bottom rates for bulk classification, extraction, re-ranking', '256K context, text + image input', 'Small enough for a mid-range laptop'],
    cons: ['Not built for deep reasoning', 'Short-form specialist — long generations suffer'],
    links: [
      { label: 'QwenLM', url: 'https://github.com/QwenLM', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/Qwen', type: 'web' },
      { label: 'Alibaba Cloud', url: 'https://www.linkedin.com/company/alibaba-cloud-computing-company', type: 'li' },
    ],
  },
  {
    id: 'nemotron-nano-9b',
    name: 'Nemotron Nano 9B V2',
    maker: 'NVIDIA',
    license: 'NVIDIA Open Model',
    priceIn: '$0.04',
    priceOut: '$0.16',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · ~6GB Q4 laptop GPU',
    pros: ['Hybrid Mamba architecture — fast on long inputs', 'Toggleable thinking mode at budget rates'],
    cons: ['Custom NVIDIA license, not OSI-approved', 'Optimised for NVIDIA silicon first'],
    links: [
      { label: 'NVIDIA', url: 'https://github.com/NVIDIA', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/nvidia', type: 'web' },
      { label: 'NVIDIA', url: 'https://www.linkedin.com/company/nvidia', type: 'li' },
    ],
  },
  {
    id: 'olmo-3-7b',
    name: 'OLMo 3 7B',
    maker: 'Ai2 (Allen Institute)',
    license: 'Apache-2.0',
    priceIn: '$0.10',
    priceOut: '$0.20',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · ~5GB Q4 — any laptop',
    pros: ['Fully open: weights, data, code, checkpoints, training logs', 'The auditable model — exactly what a public good should be', 'Think variant for open reasoning research'],
    cons: ['Trails same-size Qwen/Gemma on raw benchmarks', '65K context — mid-pack'],
    links: [
      { label: 'allenai', url: 'https://github.com/allenai', type: 'gh' },
      { label: 'allenai.org', url: 'https://allenai.org/olmo', type: 'web' },
    ],
  },
  {
    id: 'ministral-3-14b',
    name: 'Ministral 3 14B',
    maker: 'Mistral AI',
    license: 'Apache-2.0',
    priceIn: '$0.20',
    priceOut: '$0.20',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · ~9GB Q4 laptop',
    pros: ['Top of the edge family — vision + 256K context', 'Flat symmetric pricing'],
    cons: ['Priciest of the Ministral tier per token'],
    links: [
      { label: 'mistralai', url: 'https://github.com/mistralai', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/mistralai', type: 'web' },
      { label: 'Mistral AI', url: 'https://www.linkedin.com/company/mistralai', type: 'li' },
    ],
  },
  {
    id: 'ministral-3-8b',
    name: 'Ministral 3 8B',
    maker: 'Mistral AI',
    license: 'Apache-2.0',
    priceIn: '$0.15',
    priceOut: '$0.15',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · ~5GB Q4 laptop',
    pros: ['European edge workhorse — strong on EU languages', 'Low-latency routing and extraction'],
    cons: ['8B ceiling on complex chains'],
    links: [
      { label: 'mistralai', url: 'https://github.com/mistralai', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/mistralai', type: 'web' },
      { label: 'Mistral AI', url: 'https://www.linkedin.com/company/mistralai', type: 'li' },
    ],
  },
  /* ——— Phone & edge class · under 4GB ——— */
  {
    id: 'qwen35-4b',
    name: 'Qwen3.5 4B',
    maker: 'Alibaba Qwen',
    license: 'Apache-2.0 family',
    priceIn: '$0.03',
    priceOut: '$0.15',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · 3.4GB — old laptop or high-end phone',
    pros: ['Text + image input and 256K context in a 3.4GB download', 'The bulk-work bargain of the registry'],
    cons: ['4B-class judgement — keep it on rails'],
    links: [
      { label: 'QwenLM', url: 'https://github.com/QwenLM', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/Qwen', type: 'web' },
      { label: 'Alibaba Cloud', url: 'https://www.linkedin.com/company/alibaba-cloud-computing-company', type: 'li' },
    ],
  },
  {
    id: 'phi-4-mini',
    name: 'Phi-4-mini 3.8B',
    maker: 'Microsoft',
    license: 'MIT',
    priceIn: '$0.08',
    priceOut: '$0.30',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2.2GB — any laptop, big phones',
    pros: ['Best reasoning and math per gigabyte', 'MIT license'],
    cons: ['Text-only', 'Weaker world knowledge — pair it with search'],
    links: [
      { label: 'microsoft', url: 'https://github.com/microsoft', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/microsoft', type: 'web' },
      { label: 'Microsoft', url: 'https://www.linkedin.com/company/microsoft', type: 'li' },
    ],
  },
  {
    id: 'gemma-4-e4b',
    name: 'Gemma 4 E4B',
    maker: 'Google',
    license: 'Gemma license',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2.5GB — high-end phones, Raspberry Pi class',
    pros: ['Text, image and audio input on a phone', 'Native function calling at the edge', '128K context'],
    cons: ['Effective ~4.5B — an assistant, not an analyst', 'Custom license, not OSI-approved'],
    links: [
      { label: 'ai.google.dev/gemma', url: 'https://ai.google.dev/gemma', type: 'web' },
      { label: 'huggingface.co', url: 'https://huggingface.co/google', type: 'web' },
      { label: 'Google DeepMind', url: 'https://www.linkedin.com/company/googledeepmind', type: 'li' },
    ],
  },
  {
    id: 'gemma-4-e2b',
    name: 'Gemma 4 E2B',
    maker: 'Google',
    license: 'Gemma license',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~1.3GB — mid-range phones, IoT',
    pros: ['Multimodal in 1.3GB — runs on almost any current phone', 'NPU/GPU accelerated via LiteRT'],
    cons: ['Utility tier — classify, extract, summarise, stop there'],
    links: [
      { label: 'ai.google.dev/gemma', url: 'https://ai.google.dev/gemma', type: 'web' },
      { label: 'huggingface.co', url: 'https://huggingface.co/google', type: 'web' },
      { label: 'Google DeepMind', url: 'https://www.linkedin.com/company/googledeepmind', type: 'li' },
    ],
  },
  {
    id: 'llama-32-3b',
    name: 'Llama 3.2 3B',
    maker: 'Meta',
    license: 'Llama Community',
    priceIn: '$0.05',
    priceOut: '$0.33',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2GB Q4 — runs on an iPhone',
    pros: ['Best tool-calling of the tiny class', '30+ tok/s on a MacBook Air', 'Huge fine-tune ecosystem'],
    cons: ['2024 weights — showing their age', 'Community license, not OSI-approved'],
    links: [
      { label: 'meta-llama', url: 'https://github.com/meta-llama', type: 'gh' },
      { label: 'llama.com', url: 'https://www.llama.com', type: 'web' },
      { label: 'Meta', url: 'https://www.linkedin.com/company/meta', type: 'li' },
    ],
  },
  {
    id: 'llama-32-1b',
    name: 'Llama 3.2 1B',
    maker: 'Meta',
    license: 'Llama Community',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · 0.8GB — any phone, even a Pi',
    pros: ['Runs literally anywhere — old laptops, phones, single-board computers', 'The on-ramp: everyone can try local AI with it'],
    cons: ['1B-class output — draft, route, autocomplete only'],
    links: [
      { label: 'meta-llama', url: 'https://github.com/meta-llama', type: 'gh' },
      { label: 'llama.com', url: 'https://www.llama.com', type: 'web' },
      { label: 'Meta', url: 'https://www.linkedin.com/company/meta', type: 'li' },
    ],
  },
  {
    id: 'ministral-3-3b',
    name: 'Ministral 3 3B',
    maker: 'Mistral AI',
    license: 'Apache-2.0',
    priceIn: '$0.10',
    priceOut: '$0.10',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2GB — phones and edge boxes',
    pros: ['Vision + 256K context in a 3B', 'Cheapest hosted Mistral lane, flat pricing'],
    cons: ['Keep tasks narrow — 3B judgement'],
    links: [
      { label: 'mistralai', url: 'https://github.com/mistralai', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/mistralai', type: 'web' },
      { label: 'Mistral AI', url: 'https://www.linkedin.com/company/mistralai', type: 'li' },
    ],
  },
  {
    id: 'smollm3-3b',
    name: 'SmolLM3 3B',
    maker: 'Hugging Face',
    license: 'Apache-2.0',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2GB — laptops and phones',
    pros: ['Fully open training recipe and data — built to be studied', 'Dual reasoning modes in a 3B', 'Community model from the open-source home team'],
    cons: ['No serious hosted lane — self-host is the point', 'Research-first polish'],
    links: [
      { label: 'huggingface/smollm', url: 'https://github.com/huggingface/smollm', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/HuggingFaceTB', type: 'web' },
      { label: 'Hugging Face', url: 'https://www.linkedin.com/company/huggingface', type: 'li' },
    ],
  },
  {
    id: 'granite-4-micro',
    name: 'Granite 4.0 Micro',
    maker: 'IBM',
    license: 'Apache-2.0',
    priceIn: '$0.02',
    priceOut: '$0.11',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2GB — edge and enterprise laptops',
    pros: ['Enterprise-grade tiny model with ISO-certified governance', 'Hybrid Mamba — frugal memory even at long context'],
    cons: ['Conservative by design — not a creative writer'],
    links: [
      { label: 'ibm-granite', url: 'https://github.com/ibm-granite', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/ibm-granite', type: 'web' },
      { label: 'IBM', url: 'https://www.linkedin.com/company/ibm', type: 'li' },
    ],
  },
];

/* ============ WHO WE ARE LOOKING FOR — searchable examples ============ */
window.ENKI_PROFILES = [
  /* ---- Engineering (41) ---- */
  { c: "Engineering", t: "Software engineers to build Wally for web, desktop and mobile", d: 1 },
  { c: "Engineering", t: "LibreChat contributors who already know the codebase we will fork" },
  { c: "Engineering", t: "Ollama contributors to shape the local engine we source from" },
  { c: "Engineering", t: "llama.cpp and MLX hackers squeezing models onto small silicon" },
  { c: "Engineering", t: "Rust and Go systems engineers for the tooling around the mesh" },
  { c: "Engineering", t: "iOS and Android engineers to put Wally in every pocket" },
  { c: "Engineering", t: "Tauri and Electron engineers for the desktop builds" },
  { c: "Engineering", t: "Local-first sync engineers fluent in CRDTs" },
  { c: "Engineering", t: "P2P protocol engineers — libp2p, WebRTC, DHTs" },
  { c: "Engineering", t: "Security engineers to harden what 300 people ship" },
  { c: "Engineering", t: "Cryptographers for the DAO votes and signed ballots" },
  { c: "Engineering", t: "Privacy engineers who design with data minimisation by default" },
  { c: "Engineering", t: "DevOps and self-hosting veterans who run their own racks" },
  { c: "Engineering", t: "QA engineers who break things before the public does" },
  { c: "Engineering", t: "Accessibility engineers so Wally works for everyone" },
  { c: "Engineering", t: "Data engineers to keep the registries clean and queryable" },
  { c: "Engineering", t: "Web performance obsessives who count kilobytes" },
  { c: "Engineering", t: "Smart-contract engineers for one seat = one vote machinery" },
  { c: "Engineering", t: "No-code automation experts wiring our operations together" },
  { c: "Engineering", t: "Open-source maintainers who know how to run a healthy repo" },
  { c: "Engineering", t: "TypeScript and React engineers for the Wally front-end" },
  { c: "Engineering", t: "Node and Python back-end engineers for the registries" },
  { c: "Engineering", t: "MCP tool-server builders connecting Wally to everything" },
  { c: "Engineering", t: "Browser-extension engineers" },
  { c: "Engineering", t: "Linux packagers — deb, rpm, Flatpak, Nix" },
  { c: "Engineering", t: "Windows and macOS packaging and signing specialists" },
  { c: "Engineering", t: "Embedded Linux engineers" },
  { c: "Engineering", t: "Database engineers who love SQLite more than clusters" },
  { c: "Engineering", t: "API designers with taste" },
  { c: "Engineering", t: "SDK writers so others can build on Wally" },
  { c: "Engineering", t: "Reverse engineers who audit what closed vendors ship" },
  { c: "Engineering", t: "Performance profilers hunting the inference hot paths" },
  { c: "Engineering", t: "WebGPU and WASM engineers running models in the browser" },
  { c: "Engineering", t: "Compiler engineers — LLVM, MLIR and friends" },
  { c: "Engineering", t: "Kernel hackers for scheduler and memory tricks" },
  { c: "Engineering", t: "Network-protocol implementers for the sync layer" },
  { c: "Engineering", t: "Testing-infrastructure engineers — CI that never lies" },
  { c: "Engineering", t: "Release managers who cut clean, boring versions" },
  { c: "Engineering", t: "Bug-bounty hunters who tell us first" },
  { c: "Engineering", t: "Documentation engineers — docs as code, examples that run" },
  { c: "Engineering", t: "Simulation engineers stress-testing the mesh at city scale" },

  /* ---- AI research (32) ---- */
  { c: "AI research", t: "AI researchers focused on local-efficient models", d: 1 },
  { c: "AI research", t: "Quantization researchers — GGUF, AWQ, 4-bit and below" },
  { c: "AI research", t: "Distillation specialists shrinking big teachers into small students" },
  { c: "AI research", t: "Small-model pretraining researchers" },
  { c: "AI research", t: "On-device inference optimisers — NPU, Metal, Vulkan" },
  { c: "AI research", t: "NPU compiler engineers" },
  { c: "AI research", t: "Researchers of on-device RAG and personal memory" },
  { c: "AI research", t: "Federated learning researchers" },
  { c: "AI research", t: "TinyML practitioners running models on microcontrollers" },
  { c: "AI research", t: "Speech and audio model researchers for offline voice" },
  { c: "AI research", t: "Multimodal small-model researchers" },
  { c: "AI research", t: "Benchmark and eval designers we can trust" },
  { c: "AI research", t: "Dataset curators for open training corpora" },
  { c: "AI research", t: "Energy-efficiency researchers measuring joules per token" },
  { c: "AI research", t: "Alignment researchers who think small models matter too" },
  { c: "AI research", t: "MoE and sparse-model researchers for modest hardware" },
  { c: "AI research", t: "LoRA and fine-tuning practitioners" },
  { c: "AI research", t: "Post-training researchers — DPO, RLHF, open recipes" },
  { c: "AI research", t: "Synthetic-data researchers" },
  { c: "AI research", t: "Long-context efficiency researchers" },
  { c: "AI research", t: "KV-cache compression researchers" },
  { c: "AI research", t: "Speculative-decoding researchers" },
  { c: "AI research", t: "Agent researchers whose agents run fully offline" },
  { c: "AI research", t: "Vision-model researchers for on-device OCR and camera tasks" },
  { c: "AI research", t: "Robotics VLA researchers for local brains in machines" },
  { c: "AI research", t: "Recommender-system researchers who refuse surveillance" },
  { c: "AI research", t: "Interpretability researchers who open black boxes" },
  { c: "AI research", t: "Provenance and watermarking researchers" },
  { c: "AI research", t: "Open-weights release veterans from the big labs" },
  { c: "AI research", t: "Reproducibility hawks who rerun the numbers" },
  { c: "AI research", t: "Academic advisors for Institute publications" },
  { c: "AI research", t: "Model-merge tinkerers with unreasonable results" },

  /* ---- Mesh (18) ---- */
  { c: "Mesh", t: "Network engineers to design the home and office mesh", d: 1 },
  { c: "Mesh", t: "Mesh networking researchers — Thread, Zigbee, Matter, WiFi Direct" },
  { c: "Mesh", t: "Bluetooth and WiFi stack engineers for device-to-device links" },
  { c: "Mesh", t: "Telecom engineers who know what routers can really do" },
  { c: "Mesh", t: "Embedded engineers for the devices at the edge of the mesh" },
  { c: "Mesh", t: "Firmware developers for GPUs, NPUs and IoT boards" },
  { c: "Mesh", t: "Home-automation and domotics specialists" },
  { c: "Mesh", t: "Network security specialists to keep the mesh private" },
  { c: "Mesh", t: "LoRa and long-range radio experts" },
  { c: "Mesh", t: "Meshtastic and off-grid comms builders" },
  { c: "Mesh", t: "Community-network veterans — Guifi, Freifunk, NYC Mesh" },
  { c: "Mesh", t: "Rural-connectivity builders" },
  { c: "Mesh", t: "Satellite and LEO connectivity engineers" },
  { c: "Mesh", t: "mDNS and local-discovery protocol experts" },
  { c: "Mesh", t: "NAT-traversal wizards" },
  { c: "Mesh", t: "Edge-caching engineers rethinking CDNs for homes" },
  { c: "Mesh", t: "Powerline and unusual-transport networking tinkerers" },
  { c: "Mesh", t: "Municipal-broadband operators" },

  /* ---- Capital (32) ---- */
  { c: "Capital", t: "Philanthropists and investors ready to bankroll public-good AI — independence is bought in hardware and time", d: 1 },
  { c: "Capital", t: "VC partners who can point capital our way" },
  { c: "Capital", t: "Angels and philanthropists at heart" },
  { c: "Capital", t: "Foundation program officers" },
  { c: "Capital", t: "Family-office advisors curious about public goods" },
  { c: "Capital", t: "Crowdfunding veterans" },
  { c: "Capital", t: "Corporate-sponsorship connectors" },
  { c: "Capital", t: "Angel investors with exits behind them who now fund public goods" },
  { c: "Capital", t: "Emerging-market investors who see local-first AI as the leapfrog" },
  { c: "Capital", t: "Limited partners asking where capital goes after the datacenter bubble" },
  { c: "Capital", t: "Family offices allocating to resilience and digital sovereignty" },
  { c: "Capital", t: "Impact investors who measure autonomy, not just returns" },
  { c: "Capital", t: "Philanthropists ready to endow open-source AI like a public library" },
  { c: "Capital", t: "Crypto-native treasuries that fund public-good protocols" },
  { c: "Capital", t: "Quadratic-funding and Gitcoin practitioners" },
  { c: "Capital", t: "Sovereign-wealth and pension advisors who think in decades" },
  { c: "Capital", t: "Bankers who can explain us to the money world" },
  { c: "Capital", t: "CFOs to model a non-profit that never runs dry" },
  { c: "Capital", t: "Endowment managers for a war chest that outlives us" },
  { c: "Capital", t: "Fintech founders who know how money actually moves" },
  { c: "Capital", t: "Payment and settlement experts for global micro-donations" },
  { c: "Capital", t: "Cross-border giving tax advisors — 501(c)(3), EU, CH" },
  { c: "Capital", t: "Fundraisers who have closed eight-figure gifts" },
  { c: "Capital", t: "Donor-advised-fund insiders" },
  { c: "Capital", t: "EU grant specialists — Horizon, NGI, Digital Europe" },
  { c: "Capital", t: "Public-money watchdogs keeping our books honest" },
  { c: "Capital", t: "Token-market economists pricing the falling cost floor" },
  { c: "Capital", t: "Hedge-fund quants who want their models local and private" },
  { c: "Capital", t: "Corporate-development people who can route sponsorships" },
  { c: "Capital", t: "Membership-economy and micro-donation operators" },
  { c: "Capital", t: "Wealth managers whose clients keep asking about AI" },
  { c: "Capital", t: "People with money who simply want this to exist" },

  /* ---- Community (19) ---- */
  { c: "Community", t: "Discord and community managers to run the daily home of the 300", d: 1 },
  { c: "Community", t: "Social media managers — one voice across X, LinkedIn, Bluesky, Mastodon" },
  { c: "Community", t: "Discord server architects — roles, bots, onboarding flows" },
  { c: "Community", t: "Moderators who keep big communities kind and on-topic" },
  { c: "Community", t: "Reddit natives who know how a community actually talks" },
  { c: "Community", t: "TikTok and Shorts creators compressing the manifesto to 60 seconds" },
  { c: "Community", t: "Meme artists — the argument needs jokes too" },
  { c: "Community", t: "Twitch and YouTube streamers who build in public" },
  { c: "Community", t: "Telegram and Signal group operators" },
  { c: "Community", t: "Community data analysts measuring real engagement" },
  { c: "Community", t: "Ambassador-program designers for a hundred cities" },
  { c: "Community", t: "Meetup hosts for local install parties" },
  { c: "Community", t: "Hackathon organisers for Wally plugins and mesh nodes" },
  { c: "Community", t: "Developer-relations people who answer the hard GitHub issues" },
  { c: "Community", t: "Forum veterans — Discourse and older — who value slow conversation" },
  { c: "Community", t: "Growth marketers with a conscience" },
  { c: "Community", t: "Onboarding writers who make the first hour magical" },
  { c: "Community", t: "Per-language localization community leads" },
  { c: "Community", t: "Support leads who turn confused users into contributors" },

  /* ---- Hardware (21) ---- */
  { c: "Hardware", t: "Hardware engineers to advise on electronics, GPUs and NPUs" },
  { c: "Hardware", t: "Semiconductor industry veterans who know the fabs" },
  { c: "Hardware", t: "Chip designers — RISC-V and open silicon" },
  { c: "Hardware", t: "Edge-AI silicon product managers" },
  { c: "Hardware", t: "Consumer-electronics manufacturing experts" },
  { c: "Hardware", t: "Supply-chain specialists for open hardware" },
  { c: "Hardware", t: "Thermal and power engineers for fanless inference" },
  { c: "Hardware", t: "Repairability advocates — right to repair, long-lived devices" },
  { c: "Hardware", t: "Robotics engineers putting local brains in machines" },
  { c: "Hardware", t: "Solar and off-grid tinkerers running models on sunlight" },
  { c: "Hardware", t: "NPU firmware engineers across vendors — Apple, Qualcomm, Rockchip" },
  { c: "Hardware", t: "Single-board-computer community leaders — Raspberry Pi and beyond" },
  { c: "Hardware", t: "Home-server and NAS builders" },
  { c: "Hardware", t: "E-waste refurbishers giving old GPUs a second life" },
  { c: "Hardware", t: "Enclosure and 3D-printing designers" },
  { c: "Hardware", t: "Battery and power-management engineers" },
  { c: "Hardware", t: "FPGA hackers for inference" },
  { c: "Hardware", t: "Handheld and retro-hardware modders who make small machines sing" },
  { c: "Hardware", t: "Industrial designers for hardware people love" },
  { c: "Hardware", t: "Procurement experts who buy compute cheap" },
  { c: "Hardware", t: "Next-substrate researchers — photonics, analog, neuromorphic" },

  /* ---- Vision (22) ---- */
  { c: "Vision", t: "Philosophers who can help sharpen our vision" },
  { c: "Vision", t: "Ethicists of technology and autonomy" },
  { c: "Vision", t: "Historians of technology who have seen this cycle before" },
  { c: "Vision", t: "Political scientists who study power and infrastructure" },
  { c: "Vision", t: "Economists who understand collapsing cost curves" },
  { c: "Vision", t: "Game theorists for governance design" },
  { c: "Vision", t: "Sociologists of work and automation" },
  { c: "Vision", t: "Anthropologists watching what AI does to communities" },
  { c: "Vision", t: "Science-fiction writers who imagine the decentralised path" },
  { c: "Vision", t: "Futurists with their feet on the ground" },
  { c: "Vision", t: "Linguists for a truly multilingual Wally" },
  { c: "Vision", t: "Theologians — every tradition has thought about creation" },
  { c: "Vision", t: "Artists working with local models" },
  { c: "Vision", t: "Poets and novelists shaping the mythology" },
  { c: "Vision", t: "Psychologists of human–AI attachment" },
  { c: "Vision", t: "Critical-thinking educators for the AI age" },
  { c: "Vision", t: "Digital-sovereignty scholars from the Global South" },
  { c: "Vision", t: "Commons researchers — the Ostrom school" },
  { c: "Vision", t: "Sufficiency and degrowth economists" },
  { c: "Vision", t: "Cyberneticians who remember Wiener and Beer" },
  { c: "Vision", t: "Ethnographers of open-source communities" },
  { c: "Vision", t: "Scholars of digital personhood" },

  /* ---- Policy (24) ---- */
  { c: "Policy", t: "EU AI Act specialists" },
  { c: "Policy", t: "Lawyers for association, foundation and non-profit law — CH, US, EU" },
  { c: "Policy", t: "Open-source licensing lawyers" },
  { c: "Policy", t: "Data-protection lawyers — GDPR and beyond" },
  { c: "Policy", t: "Former regulators who know how the rules get written" },
  { c: "Policy", t: "Policy advisors inside governments" },
  { c: "Policy", t: "Diplomats and multilateral negotiators" },
  { c: "Policy", t: "Standards-body participants — IETF, IEEE, W3C" },
  { c: "Policy", t: "Digital-rights activists" },
  { c: "Policy", t: "Think-tank fellows on AI and society" },
  { c: "Policy", t: "Competition and antitrust experts" },
  { c: "Policy", t: "Telecom regulation specialists" },
  { c: "Policy", t: "US state-level AI policy specialists" },
  { c: "Policy", t: "UN and multilateral AI-governance advisors" },
  { c: "Policy", t: "African Union and ASEAN digital-policy experts" },
  { c: "Policy", t: "Export-control specialists — chips and model weights" },
  { c: "Policy", t: "Procurement-law experts for public-sector deployments" },
  { c: "Policy", t: "Consumer-protection lawyers" },
  { c: "Policy", t: "IP litigators for open-source defence" },
  { c: "Policy", t: "Whistleblower-protection lawyers" },
  { c: "Policy", t: "Election-integrity technologists" },
  { c: "Policy", t: "Accessibility-regulation experts" },
  { c: "Policy", t: "Spectrum-policy specialists for the mesh" },
  { c: "Policy", t: "Charity and association regulators turned advisors" },

  /* ---- Media (22) ---- */
  { c: "Media", t: "Tech journalists who can hold power to account" },
  { c: "Media", t: "Documentary filmmakers" },
  { c: "Media", t: "Podcasters and YouTubers who explain hard things simply" },
  { c: "Media", t: "Science communicators" },
  { c: "Media", t: "Technical writers for docs people actually read" },
  { c: "Media", t: "Translators to carry the manifesto into every language" },
  { c: "Media", t: "Newsletter operators who grow real audiences" },
  { c: "Media", t: "Brand and graphic designers" },
  { c: "Media", t: "Motion designers and illustrators" },
  { c: "Media", t: "Typographers who care about the small stuff" },
  { c: "Media", t: "UX researchers listening to real users" },
  { c: "Media", t: "Investigative reporters on datacenter economics" },
  { c: "Media", t: "Data journalists visualising the registries" },
  { c: "Media", t: "Radio and podcast producers" },
  { c: "Media", t: "Book editors and publishers" },
  { c: "Media", t: "PR operators who place stories without spin" },
  { c: "Media", t: "Crisis-communication specialists" },
  { c: "Media", t: "Video essayists" },
  { c: "Media", t: "Photographers documenting the mesh in real homes" },
  { c: "Media", t: "Copywriters who can compress an argument" },
  { c: "Media", t: "School-curriculum writers" },
  { c: "Media", t: "Multilingual subtitlers and dubbing artists" },

  /* ---- Networks (25) ---- */
  { c: "Networks", t: "People inside frontier labs who share our worries" },
  { c: "Networks", t: "People inside governments and public institutions" },
  { c: "Networks", t: "University professors and lab directors" },
  { c: "Networks", t: "Deans and rectors who can open academic doors" },
  { c: "Networks", t: "Open-source foundation insiders — Linux, Mozilla, Wikimedia" },
  { c: "Networks", t: "Organisers of conferences and hackathons" },
  { c: "Networks", t: "People well connected around AI journalism and research" },
  { c: "Networks", t: "Municipal and city-level innovation officers" },
  { c: "Networks", t: "Educators teaching local AI in schools and universities" },
  { c: "Networks", t: "Librarians and archivists who think in public goods" },
  { c: "Networks", t: "NGO operators who have scaled volunteer networks" },
  { c: "Networks", t: "Community organisers from outside tech entirely" },
  { c: "Networks", t: "Alumni networks of big-tech leavers" },
  { c: "Networks", t: "Diaspora tech communities" },
  { c: "Networks", t: "Hacker-space and maker-space organisers" },
  { c: "Networks", t: "Chaos Computer Club and demoscene folks" },
  { c: "Networks", t: "Ham-radio license holders and their clubs" },
  { c: "Networks", t: "Open-data activists inside city halls" },
  { c: "Networks", t: "Cooperative and platform-coop leaders" },
  { c: "Networks", t: "Union technologists" },
  { c: "Networks", t: "Faith-community organisers" },
  { c: "Networks", t: "Civic-club connectors — Rotary to sports clubs" },
  { c: "Networks", t: "Members of scientific societies and academies" },
  { c: "Networks", t: "Festival programmers where art meets tech" },
  { c: "Networks", t: "Wikipedia editors who keep the record straight" },

  /* ---- Operations (21) ---- */
  { c: "Operations", t: "Accountants and auditors for transparent books" },
  { c: "Operations", t: "Treasurers for a DAO-governed budget" },
  { c: "Operations", t: "Governance experts for a 300-member assembly" },
  { c: "Operations", t: "Facilitators and mediators for hard debates" },
  { c: "Operations", t: "Talent scouts to help select the rest of the 300" },
  { c: "Operations", t: "Project managers who ship without corporate theatre" },
  { c: "Operations", t: "Grant writers fluent in public funding" },
  { c: "Operations", t: "Psychologists who keep communities healthy" },
  { c: "Operations", t: "DAO experts who have run one-member-one-vote governance in production" },
  { c: "Operations", t: "Election administrators for the signed ballots" },
  { c: "Operations", t: "Legal-operations managers for a distributed association" },
  { c: "Operations", t: "Volunteer-HR designers" },
  { c: "Operations", t: "Fair-compensation designers for non-profit work" },
  { c: "Operations", t: "Procurement and vendor managers" },
  { c: "Operations", t: "Insurance experts for a global association" },
  { c: "Operations", t: "Data-protection officers" },
  { c: "Operations", t: "Internal-tools builders — wikis, CRMs, dashboards" },
  { c: "Operations", t: "Meeting designers who keep 300 people efficient" },
  { c: "Operations", t: "Ombudspersons for disputes" },
  { c: "Operations", t: "Archivists of decisions and minutes" },
  { c: "Operations", t: "Burnout-prevention coaches" },

  /* ---- Science (13) ---- */
  { c: "Science", t: "Physicists who compute at the edge" },
  { c: "Science", t: "Neuroscientists comparing brains and small models" },
  { c: "Science", t: "Mathematicians of compression and information" },
  { c: "Science", t: "Climate scientists counting AI's real footprint" },
  { c: "Science", t: "Energy-grid researchers" },
  { c: "Science", t: "Materials scientists for greener silicon" },
  { c: "Science", t: "Field epidemiologists who need offline AI" },
  { c: "Science", t: "Doctors and nurses using local AI in clinics" },
  { c: "Science", t: "Farmers and agronomists running models off-grid" },
  { c: "Science", t: "Marine and polar researchers — AI where there is no signal" },
  { c: "Science", t: "Astronomers who process locally by necessity" },
  { c: "Science", t: "Citizen-science coordinators" },
  { c: "Science", t: "Psychiatrists studying AI companionship" },

  /* ---- Education (10) ---- */
  { c: "Education", t: "Teachers bringing local AI into classrooms" },
  { c: "Education", t: "University lecturers building curricula on open models" },
  { c: "Education", t: "Vocational trainers for the AI-maintenance jobs to come" },
  { c: "Education", t: "Children's educators who explain AI without fear" },
  { c: "Education", t: "Digital-inclusion and adult-literacy workers" },
  { c: "Education", t: "Homeschooling network organisers" },
  { c: "Education", t: "MOOC and open-courseware creators" },
  { c: "Education", t: "School-IT administrators who deploy at scale" },
  { c: "Education", t: "Education-ministry insiders" },
  { c: "Education", t: "Student AI-club leaders" }
];
