/* Enki Registry — seed data.
   These entries are illustrative examples to demonstrate the registry format.
   Real entries are community-submitted and human-reviewed before listing. */

window.ENKI_SEED = [
  {
    id: 'clippy',
    repo: 'paulfxyz/clippy',
    name: 'Clippy',
    url: 'https://clippy.legal',
    desc: 'AI contract analyst that reviews, redlines and explains legal documents in plain language.',
    tools: ['Perplexity Computer'],
    models: ['Claude Sonnet 4.5', 'GPT-5'],
    vibe: 98,
    cost: 210,
    date: '2026-05-02',
    sample: true,
  },
  {
    id: 'junk',
    repo: 'paulfxyz/junk',
    name: 'Junk',
    url: 'https://thejunk.app',
    desc: 'Cross-platform floating scratchpad that lives above every window — capture anything, everywhere.',
    tools: ['Claude Code'],
    models: ['Claude Opus 4.1'],
    vibe: 95,
    cost: 145,
    date: '2026-03-18',
    sample: true,
  },
  {
    id: 'mercury',
    repo: 'paulfxyz/mercury',
    name: 'Mercury',
    url: 'https://github.com/paulfxyz/mercury',
    desc: 'Multi-model inquiry app: ask once, get a consensus answer synthesised across frontier models.',
    tools: ['Perplexity Computer'],
    models: ['GPT-5', 'Claude Sonnet 4.5', 'Gemini 2.5 Pro'],
    vibe: 100,
    cost: 95,
    date: '2026-01-27',
    sample: true,
  },
  {
    id: 'hollr',
    repo: 'paulfxyz/hollr',
    name: 'Hollr',
    url: 'https://github.com/paulfxyz/hollr',
    desc: 'Encrypted public messaging and link platform — shout into the void, keep the keys.',
    tools: ['Claude Code', 'Cursor'],
    models: ['Claude Sonnet 4.5'],
    vibe: 92,
    cost: 180,
    date: '2025-11-09',
    sample: true,
  },
  {
    id: 'mang',
    repo: 'paulfxyz/mang',
    name: 'Mang',
    url: 'https://github.com/paulfxyz/mang',
    desc: 'Natural-language-to-terminal CLI written in Rust — describe the command, mang runs it.',
    tools: ['Claude Code'],
    models: ['Claude Opus 4.1', 'Qwen3-Coder (local)'],
    vibe: 100,
    cost: 62,
    date: '2025-12-14',
    sample: true,
  },
  {
    id: 'bacchus',
    repo: 'paulfxyz/bacchus',
    name: 'Bacchus',
    url: 'https://github.com/paulfxyz/bacchus',
    desc: 'AI sommelier that pairs wines with meals, moods and budgets from a self-hosted model.',
    tools: ['Perplexity Computer'],
    models: ['Mistral Large', 'Llama 3.3 70B (local)'],
    vibe: 96,
    cost: 88,
    date: '2026-02-21',
    sample: true,
  },
  {
    id: 'tetris',
    repo: 'paulfxyz/tetris',
    name: 'Tetris by Paul',
    url: 'https://github.com/paulfxyz/tetris',
    desc: 'A polished browser Tetris, vibe-coded end-to-end in one afternoon and shipped to Product Hunt.',
    tools: ['Perplexity Computer'],
    models: ['Claude Sonnet 4.5'],
    vibe: 100,
    cost: 9,
    date: '2026-04-11',
    sample: true,
  },
  {
    id: 'gary',
    name: 'Gary',
    url: 'https://paulfleury.com',
    desc: 'An AI email & digital-hygiene coach that keeps your inbox — and your habits — clean.',
    tools: ['Claude Code', 'Ollama'],
    models: ['GPT-5', 'Gemma 3 27B (local)'],
    vibe: 90,
    cost: 240,
    date: '2025-10-03',
    sample: true,
  },
];

/* Enki Model Registry — open-weight models validated by members.
   Focus: models best adapted to self-hosting on limited hardware — a laptop,
   a desktop, even a phone. Prices: hosted-API reference rates per 1M tokens
   (Aug 2026); self-hosting trades those for hardware + energy — never "free".
   Sources: openrouter.ai, artificialanalysis.ai, mistral.ai/pricing,
   pricepertoken.com, cloudprice.net, prismml.com, allenai.org. */

window.ENKI_MODELS = [
  /* ——— Desktop class · 12–32GB GPU or Mac ——— */
  {
    id: 'qwen36-27b',
    name: 'Qwen3.6 27B',
    maker: 'Alibaba Qwen',
    license: 'Apache-2.0 family',
    priceIn: '$0.29',
    priceOut: '$2.40',
    selfHost: 'Self-host ≈ $0.03–0.70 /1M · ~17GB Q4 — 24GB GPU / 32GB Mac',
    pros: ['The strongest open model that still fits one consumer GPU', '262K context, 201 languages', 'Reasoning and non-reasoning modes in one set of weights'],
    cons: ['Hosted output rate adds up on long reasoning chains', 'Needs the full 24GB card — not a thin-laptop model'],
    links: [
      { label: 'QwenLM', url: 'https://github.com/QwenLM', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/Qwen', type: 'web' },
      { label: 'Alibaba Cloud', url: 'https://www.linkedin.com/company/alibaba-cloud-computing-company', type: 'li' },
    ],
  },
  {
    id: 'gemma-4-31b',
    name: 'Gemma 4 31B',
    maker: 'Google',
    license: 'Gemma license',
    priceIn: '$0.20',
    priceOut: '$0.20',
    selfHost: 'Self-host ≈ $0.03–0.70 /1M · 24GB GPU',
    pros: ['Flat in/out pricing — easy to budget', 'Single-GPU friendly — the local starting point', 'First-class Ollama / llama.cpp support'],
    cons: ['31B dense ceiling — outclassed on hard reasoning', 'Custom license, not OSI-approved'],
    links: [
      { label: 'ai.google.dev/gemma', url: 'https://ai.google.dev/gemma', type: 'web' },
      { label: 'huggingface.co', url: 'https://huggingface.co/google', type: 'web' },
      { label: 'Google DeepMind', url: 'https://www.linkedin.com/company/googledeepmind', type: 'li' },
    ],
  },
  {
    id: 'mistral-small-4',
    name: 'Mistral Small 4',
    maker: 'Mistral AI',
    license: 'Apache-2.0',
    priceIn: '$0.15',
    priceOut: '$0.60',
    selfHost: 'Self-host ≈ $0.03–0.70 /1M · 24GB GPU',
    pros: ['Best-in-class small model for EU-hosted work', 'Runs well on a single 24GB card'],
    cons: ['Small-model ceiling on multi-step reasoning'],
    links: [
      { label: 'mistralai', url: 'https://github.com/mistralai', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/mistralai', type: 'web' },
      { label: 'Mistral AI', url: 'https://www.linkedin.com/company/mistralai', type: 'li' },
    ],
  },
  {
    id: 'qwen3-coder-next',
    name: 'Qwen3 Coder Next',
    maker: 'Alibaba Qwen',
    license: 'Apache-2.0 family',
    priceIn: '$0.12',
    priceOut: '$0.75',
    selfHost: 'Self-host ≈ $0.03–0.70 /1M · 32GB-class GPU',
    pros: ['Code planning & tool-use specialist below mid-tier pricing', '256K context'],
    cons: ['Output is 6× its input price — long generations skew costly'],
    links: [
      { label: 'QwenLM', url: 'https://github.com/QwenLM', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/Qwen', type: 'web' },
      { label: 'Alibaba Cloud', url: 'https://www.linkedin.com/company/alibaba-cloud-computing-company', type: 'li' },
    ],
  },
  {
    id: 'phi-4',
    name: 'Phi-4 14B',
    maker: 'Microsoft',
    license: 'MIT',
    priceIn: '$0.07',
    priceOut: '$0.14',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · 12GB GPU / 16GB Mac',
    pros: ['Reasoning and math far above its weight class', 'MIT license, no strings', 'Fits a 12GB card with room to spare'],
    cons: ['16K context — short for agent loops', 'Text-only'],
    links: [
      { label: 'microsoft', url: 'https://github.com/microsoft', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/microsoft', type: 'web' },
      { label: 'Microsoft', url: 'https://www.linkedin.com/company/microsoft', type: 'li' },
    ],
  },
  /* ——— Laptop class · 4–16GB ——— */
  {
    id: 'gpt-oss-20b',
    name: 'gpt-oss-20b',
    maker: 'OpenAI',
    license: 'Apache-2.0',
    priceIn: '$0.03',
    priceOut: '$0.13',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · 16GB consumer GPU / laptop',
    pros: ['Runs on a 16GB consumer GPU or recent laptop', 'Apache-2.0, no strings', 'Adjustable reasoning effort'],
    cons: ['20B-class ceiling — delegation-tier only', 'Behind newer small models on benchmarks'],
    links: [
      { label: 'openai/gpt-oss', url: 'https://github.com/openai/gpt-oss', type: 'gh' },
      { label: 'ollama.com', url: 'https://ollama.com/library/gpt-oss', type: 'web' },
      { label: 'OpenAI', url: 'https://www.linkedin.com/company/openai', type: 'li' },
    ],
  },
  {
    id: 'bonsai-27b',
    name: 'Bonsai 27B',
    maker: 'PrismML',
    license: 'Apache-2.0',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · 5.9GB ternary laptop / 3.9GB 1-bit phone',
    pros: ['27B-class reasoning in 3.9GB — the first of its size to run on a phone', '262K context, multimodal, tool calling', '~11 tok/s on an iPhone 17 Pro Max, fully offline'],
    cons: ['1-bit quantisation keeps ~90% of full-precision quality — not 100%', 'Needs recent silicon (MLX / CUDA / WebGPU kernels)'],
    links: [
      { label: 'prismml.com', url: 'https://prismml.com', type: 'web' },
      { label: 'huggingface.co', url: 'https://huggingface.co/prism-ml', type: 'web' },
    ],
  },
  {
    id: 'qwen35-9b',
    name: 'Qwen3.5 9B',
    maker: 'Alibaba Qwen',
    license: 'Apache-2.0 family',
    priceIn: '$0.05',
    priceOut: '$0.15',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · 6.6GB — any recent laptop',
    pros: ['Rock-bottom rates for bulk classification, extraction, re-ranking', '256K context, text + image input', 'Small enough for a mid-range laptop'],
    cons: ['Not built for deep reasoning', 'Short-form specialist — long generations suffer'],
    links: [
      { label: 'QwenLM', url: 'https://github.com/QwenLM', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/Qwen', type: 'web' },
      { label: 'Alibaba Cloud', url: 'https://www.linkedin.com/company/alibaba-cloud-computing-company', type: 'li' },
    ],
  },
  {
    id: 'nemotron-nano-9b',
    name: 'Nemotron Nano 9B V2',
    maker: 'NVIDIA',
    license: 'NVIDIA Open Model',
    priceIn: '$0.04',
    priceOut: '$0.16',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · ~6GB Q4 laptop GPU',
    pros: ['Hybrid Mamba architecture — fast on long inputs', 'Toggleable thinking mode at budget rates'],
    cons: ['Custom NVIDIA license, not OSI-approved', 'Optimised for NVIDIA silicon first'],
    links: [
      { label: 'NVIDIA', url: 'https://github.com/NVIDIA', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/nvidia', type: 'web' },
      { label: 'NVIDIA', url: 'https://www.linkedin.com/company/nvidia', type: 'li' },
    ],
  },
  {
    id: 'olmo-3-7b',
    name: 'OLMo 3 7B',
    maker: 'Ai2 (Allen Institute)',
    license: 'Apache-2.0',
    priceIn: '$0.10',
    priceOut: '$0.20',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · ~5GB Q4 — any laptop',
    pros: ['Fully open: weights, data, code, checkpoints, training logs', 'The auditable model — exactly what a public good should be', 'Think variant for open reasoning research'],
    cons: ['Trails same-size Qwen/Gemma on raw benchmarks', '65K context — mid-pack'],
    links: [
      { label: 'allenai', url: 'https://github.com/allenai', type: 'gh' },
      { label: 'allenai.org', url: 'https://allenai.org/olmo', type: 'web' },
    ],
  },
  {
    id: 'ministral-3-14b',
    name: 'Ministral 3 14B',
    maker: 'Mistral AI',
    license: 'Apache-2.0',
    priceIn: '$0.20',
    priceOut: '$0.20',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · ~9GB Q4 laptop',
    pros: ['Top of the edge family — vision + 256K context', 'Flat symmetric pricing'],
    cons: ['Priciest of the Ministral tier per token'],
    links: [
      { label: 'mistralai', url: 'https://github.com/mistralai', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/mistralai', type: 'web' },
      { label: 'Mistral AI', url: 'https://www.linkedin.com/company/mistralai', type: 'li' },
    ],
  },
  {
    id: 'ministral-3-8b',
    name: 'Ministral 3 8B',
    maker: 'Mistral AI',
    license: 'Apache-2.0',
    priceIn: '$0.15',
    priceOut: '$0.15',
    selfHost: 'Self-host ≈ $0.01–0.12 /1M · ~5GB Q4 laptop',
    pros: ['European edge workhorse — strong on EU languages', 'Low-latency routing and extraction'],
    cons: ['8B ceiling on complex chains'],
    links: [
      { label: 'mistralai', url: 'https://github.com/mistralai', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/mistralai', type: 'web' },
      { label: 'Mistral AI', url: 'https://www.linkedin.com/company/mistralai', type: 'li' },
    ],
  },
  /* ——— Phone & edge class · under 4GB ——— */
  {
    id: 'qwen35-4b',
    name: 'Qwen3.5 4B',
    maker: 'Alibaba Qwen',
    license: 'Apache-2.0 family',
    priceIn: '$0.03',
    priceOut: '$0.15',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · 3.4GB — old laptop or high-end phone',
    pros: ['Text + image input and 256K context in a 3.4GB download', 'The bulk-work bargain of the registry'],
    cons: ['4B-class judgement — keep it on rails'],
    links: [
      { label: 'QwenLM', url: 'https://github.com/QwenLM', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/Qwen', type: 'web' },
      { label: 'Alibaba Cloud', url: 'https://www.linkedin.com/company/alibaba-cloud-computing-company', type: 'li' },
    ],
  },
  {
    id: 'phi-4-mini',
    name: 'Phi-4-mini 3.8B',
    maker: 'Microsoft',
    license: 'MIT',
    priceIn: '$0.08',
    priceOut: '$0.30',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2.2GB — any laptop, big phones',
    pros: ['Best reasoning and math per gigabyte', 'MIT license'],
    cons: ['Text-only', 'Weaker world knowledge — pair it with search'],
    links: [
      { label: 'microsoft', url: 'https://github.com/microsoft', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/microsoft', type: 'web' },
      { label: 'Microsoft', url: 'https://www.linkedin.com/company/microsoft', type: 'li' },
    ],
  },
  {
    id: 'gemma-4-e4b',
    name: 'Gemma 4 E4B',
    maker: 'Google',
    license: 'Gemma license',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2.5GB — high-end phones, Raspberry Pi class',
    pros: ['Text, image and audio input on a phone', 'Native function calling at the edge', '128K context'],
    cons: ['Effective ~4.5B — an assistant, not an analyst', 'Custom license, not OSI-approved'],
    links: [
      { label: 'ai.google.dev/gemma', url: 'https://ai.google.dev/gemma', type: 'web' },
      { label: 'huggingface.co', url: 'https://huggingface.co/google', type: 'web' },
      { label: 'Google DeepMind', url: 'https://www.linkedin.com/company/googledeepmind', type: 'li' },
    ],
  },
  {
    id: 'gemma-4-e2b',
    name: 'Gemma 4 E2B',
    maker: 'Google',
    license: 'Gemma license',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~1.3GB — mid-range phones, IoT',
    pros: ['Multimodal in 1.3GB — runs on almost any current phone', 'NPU/GPU accelerated via LiteRT'],
    cons: ['Utility tier — classify, extract, summarise, stop there'],
    links: [
      { label: 'ai.google.dev/gemma', url: 'https://ai.google.dev/gemma', type: 'web' },
      { label: 'huggingface.co', url: 'https://huggingface.co/google', type: 'web' },
      { label: 'Google DeepMind', url: 'https://www.linkedin.com/company/googledeepmind', type: 'li' },
    ],
  },
  {
    id: 'llama-32-3b',
    name: 'Llama 3.2 3B',
    maker: 'Meta',
    license: 'Llama Community',
    priceIn: '$0.05',
    priceOut: '$0.33',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2GB Q4 — runs on an iPhone',
    pros: ['Best tool-calling of the tiny class', '30+ tok/s on a MacBook Air', 'Huge fine-tune ecosystem'],
    cons: ['2024 weights — showing their age', 'Community license, not OSI-approved'],
    links: [
      { label: 'meta-llama', url: 'https://github.com/meta-llama', type: 'gh' },
      { label: 'llama.com', url: 'https://www.llama.com', type: 'web' },
      { label: 'Meta', url: 'https://www.linkedin.com/company/meta', type: 'li' },
    ],
  },
  {
    id: 'llama-32-1b',
    name: 'Llama 3.2 1B',
    maker: 'Meta',
    license: 'Llama Community',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · 0.8GB — any phone, even a Pi',
    pros: ['Runs literally anywhere — old laptops, phones, single-board computers', 'The on-ramp: everyone can try local AI with it'],
    cons: ['1B-class output — draft, route, autocomplete only'],
    links: [
      { label: 'meta-llama', url: 'https://github.com/meta-llama', type: 'gh' },
      { label: 'llama.com', url: 'https://www.llama.com', type: 'web' },
      { label: 'Meta', url: 'https://www.linkedin.com/company/meta', type: 'li' },
    ],
  },
  {
    id: 'ministral-3-3b',
    name: 'Ministral 3 3B',
    maker: 'Mistral AI',
    license: 'Apache-2.0',
    priceIn: '$0.10',
    priceOut: '$0.10',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2GB — phones and edge boxes',
    pros: ['Vision + 256K context in a 3B', 'Cheapest hosted Mistral lane, flat pricing'],
    cons: ['Keep tasks narrow — 3B judgement'],
    links: [
      { label: 'mistralai', url: 'https://github.com/mistralai', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/mistralai', type: 'web' },
      { label: 'Mistral AI', url: 'https://www.linkedin.com/company/mistralai', type: 'li' },
    ],
  },
  {
    id: 'smollm3-3b',
    name: 'SmolLM3 3B',
    maker: 'Hugging Face',
    license: 'Apache-2.0',
    priceIn: '—',
    priceOut: '—',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2GB — laptops and phones',
    pros: ['Fully open training recipe and data — built to be studied', 'Dual reasoning modes in a 3B', 'Community model from the open-source home team'],
    cons: ['No serious hosted lane — self-host is the point', 'Research-first polish'],
    links: [
      { label: 'huggingface/smollm', url: 'https://github.com/huggingface/smollm', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/HuggingFaceTB', type: 'web' },
      { label: 'Hugging Face', url: 'https://www.linkedin.com/company/huggingface', type: 'li' },
    ],
  },
  {
    id: 'granite-4-micro',
    name: 'Granite 4.0 Micro',
    maker: 'IBM',
    license: 'Apache-2.0',
    priceIn: '$0.02',
    priceOut: '$0.11',
    selfHost: 'Self-host ≈ $0.005–0.05 /1M · ~2GB — edge and enterprise laptops',
    pros: ['Enterprise-grade tiny model with ISO-certified governance', 'Hybrid Mamba — frugal memory even at long context'],
    cons: ['Conservative by design — not a creative writer'],
    links: [
      { label: 'ibm-granite', url: 'https://github.com/ibm-granite', type: 'gh' },
      { label: 'huggingface.co', url: 'https://huggingface.co/ibm-granite', type: 'web' },
      { label: 'IBM', url: 'https://www.linkedin.com/company/ibm', type: 'li' },
    ],
  },
];
